### ISSUE TITLE
Were I can demo the ethroulette?

### ISSUE THREAD

**Issue by Npizza** [rkalis/ethroulette#3]
is any online site that interacts with the contracts?

**Comment by rkalis** [comment]
There isn't currently, as I'm not actively working on this project any more. I could probably host a version of the frontend code running against a test net so it can be demo'd more easily. I'll see if I can do that some time in the future. In the mean time you can also clone the repository and follow the installation instructions if you want.

**Comment by rkalis** [comment]
I gave the project some updates and love today, and also hosted a version on my domain. So you can interact with the contracts through https://ethroulette.kalis.me/ (only works agains Rinkeby for now). Also note that the project is in a very immature state, so be careful with your Rinkeby ETH 😉
